# примеры API-запросов

# создать датчик
POST http://localhost:8000/api/sensors/
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "title": "sens_7",
  "description": "гараж"
}

###
# получить список датчиков
GET http://localhost:8000/api/sensors/

###

###
# получить данные одного датчика
GET http://localhost:8000/api/sensor/6/

###
# внести изменения в датчик (название, описание)
PUT http://localhost:8000/api/sensor/up/5/
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "title": "sens_6"
}

###
# добавление показаний от конкретного сенсора
POST http://localhost:8000/api/measurements/
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "sensor": "4",
  "temperature": "20"
}
